services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: n8n_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:3.3
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - kafka_data:/bitnami/kafka

  api:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/n8n_clone?sslmode=disable
      - KAFKA_BROKER=kafka:9092

  worker:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.worker
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

volumes:
  postgres_data:
  kafka_data:
